### PR TITLE
Dark and Light theme of timetable

### PR DESCRIPTION
**Pull request by Kiyo-0**

### CODE REVIEW

**Comment by h-anonymous04** [comment]
The table is not looking as it should!

your output:

image

**Comment by h-anonymous04** [comment]
the output is not as it should be!
your output:
image

**Comment by Kiyo-0** [comment]
> the output is not as it should be!
> your output:
> image
> 
> 
> Still have to link css file it's not linked directly

**Comment by h-anonymous04** [comment]
@Kiyo-0 css is working as it should! still the result is same!

**Comment by Kiyo-0** [comment]
> @Kiyo-0 css is working as it should! still the result is same!

image
it's working here but not showing in angular

**Comment by Kiyo-0** [comment]
> > @Kiyo-0 css is working as it should! still the result is same!
> 
> image it's working here but not showing in angular

image

upper one is live previw and this one is angular

**Pull request closed without merging**
